"""Private fixed-plan worker; called only by simulated_lab.run_simulation."""
import contextlib
import json
import os
from pathlib import Path
import sys


def main():
    # -I excludes the source tree; add only this installed package's source root.
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from opendot_engineering.adapters.simulated_lab import _claims, _json, _request, _versions, MAX_DOCUMENTS

    request = json.loads(sys.stdin.buffer.read(4096))
    request = _request(**request)
    _versions()
    # Set before the first ophyd import. No EPICS client is selected or used.
    os.environ["OPHYD_CONTROL_LAYER"] = "dummy"
    from bluesky import RunEngine
    from bluesky import plan_stubs as bps
    from bluesky.preprocessors import run_wrapper
    from bluesky.utils import RunEngineInterrupted
    from ophyd.sim import SynAxis, SynSignal

    motor = SynAxis(name="sim_axis", delay=0, egu="simulated_unit")
    failing = False

    def reading():
        if failing:
            raise RuntimeError("INJECTED_FAKE_DETECTOR_FAILURE")
        return 2 * motor.position + 1

    detector = SynSignal(func=reading, name="sim_detector", exposure_time=0)
    engine = RunEngine({}, call_returns_result=True)
    terminal = None
    count = 0
    stream = os.fdopen(int(sys.argv[1]), "ab", buffering=0)

    def capture(name, document):
        nonlocal terminal, count
        count += 1
        if count > MAX_DOCUMENTS:
            raise RuntimeError("DOCUMENT_BOUND_EXCEEDED")
        raw = _json({"name": name, "doc": document})
        if stream.write(raw) != len(raw):
            raise OSError("INCOMPLETE_DOCUMENT_WRITE")
        os.fsync(stream.fileno())
        if name == "stop":
            terminal = {"exit_status": document["exit_status"], "stop_uid": document["uid"]}

    engine.subscribe(capture)
    engine.ignore_callback_exceptions = False

    def fixed_plan():
        nonlocal failing
        if request["scenario"] == "simulated_abort":
            yield from bps.pause()
        for point in request["setpoints"]:
            yield from bps.abs_set(motor, point, group="move")
            yield from bps.wait(group="move", timeout=1)
            failing = request["scenario"] == "fake_failure"
            yield from bps.trigger_and_read([motor, detector])

    try:
        with contextlib.redirect_stdout(sys.stderr):
            try:
                engine(run_wrapper(fixed_plan(), md={**_claims(),
                    "plan_name": "bounded_simulated_set_read", "simulation_request": request}))
            except RunEngineInterrupted:
                engine.abort("INJECTED_SIMULATED_ABORT")
            except RuntimeError:
                # A real RunStop generated by Bluesky is mandatory, even for failure.
                if terminal is None or terminal["exit_status"] != "fail":
                    raise
        if terminal is None or not engine.state.is_idle:
            raise RuntimeError("MISSING_TERMINAL_DOCUMENT")
        print(json.dumps(terminal))
    finally:
        stream.close()
        motor.destroy()
        detector.destroy()


if __name__ == "__main__":
    main()
